# site settings

title: Koray Balci
description: My personal web presence
taglong: My personal web presence
tagshort: home
url: https://koraybalci.com
baseurl: ""
permalink: pretty
repo: https://github.com/koraybalci/koraybalci.github.io

# author settings

author:
  name: Koray Balci
  email: mentat@gmail.com
photo: /assets/png/koray.png

# social media links

social:  
  github: koraybalci
  linkedin: koraybalci
  stackoverflow: 68887/mentat
  twitter: koraybalci

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
