# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Koray Balcı
tagline:          developer blog?
url:              http://koraybalci.github.io
paginate:         1
baseurl:          /
author:
  name:           Koray Balcı
  url:            https://twitter.com/koraybalci
  email:          koraybalci@gmail.com

# Custom vars
version:          1.0.0

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE.md
    - README.md
